language: c

git:
    submodules: true

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/Drivewaylights.ino

install:
    - pip install -U platformio

script:
    - platformio lib update
    - platformio run

